/**
 * Generate the decorative brand motifs used by the CSS:
 *   arcs.svg      — thin concentric strokes behind the hero (from the brand book)
 *   favicon.svg   — the symbol on a plum tile
 *   motifs.css    — data-URI custom properties for small inline marks
 */
import { readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'

const ROOT = path.resolve(import.meta.dirname, '..')
const BRAND = path.join(ROOT, 'assets', 'brand')

const enc = (svg) =>
  `url("data:image/svg+xml,${encodeURIComponent(svg.replace(/\s+/g, ' ').trim())
    .replace(/'/g, '%27')
    .replace(/"/g, '%22')}")`

const main = async () => {
  const mark = (await readFile(path.join(BRAND, 'mark-navy.svg'), 'utf8')).trim()
  const markWhite = (await readFile(path.join(BRAND, 'mark-white.svg'), 'utf8')).trim()

  // Concentric arcs — the brand book uses these thin rings as a background device.
  const arcs = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 800" fill="none" aria-hidden="true">
  <g stroke-linecap="round">
    <circle cx="400" cy="400" r="150" stroke="#60DADB" stroke-width="1" opacity=".35"/>
    <circle cx="400" cy="400" r="232" stroke="#D9F650" stroke-width="1" opacity=".28"/>
    <circle cx="400" cy="400" r="316" stroke="#60DADB" stroke-width="1" opacity=".22"/>
    <circle cx="400" cy="400" r="399" stroke="#D9F650" stroke-width="1" opacity=".16"/>
    <path d="M400 68a332 332 0 0 1 288 166" stroke="#60DADB" stroke-width="2.5" opacity=".5"/>
    <path d="M117 566a316 316 0 0 1-32-166" stroke="#D9F650" stroke-width="2.5" opacity=".45"/>
  </g>
</svg>`
  await writeFile(path.join(BRAND, 'arcs.svg'), arcs, 'utf8')

  const inner = markWhite.replace(/^[\s\S]*?<svg[^>]*viewBox="([^"]+)"[^>]*>/, '').replace(/<\/svg>\s*$/, '')
  const vb = markWhite.match(/viewBox="([^"]+)"/)[1]
  const [vx, vy, vw, vh] = vb.split(/\s+/).map(Number)
  const pad = Math.max(vw, vh) * 0.28
  const size = Math.max(vw, vh) + pad * 2
  const favicon = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${size.toFixed(2)} ${size.toFixed(2)}">
  <rect width="${size.toFixed(2)}" height="${size.toFixed(2)}" rx="${(size * 0.22).toFixed(2)}" fill="#080C29"/>
  <g transform="translate(${(pad - vx + (Math.max(vw, vh) - vw) / 2).toFixed(2)} ${(pad - vy + (Math.max(vw, vh) - vh) / 2).toFixed(2)})">${inner}</g>
</svg>`
  await writeFile(path.join(BRAND, 'favicon.svg'), favicon, 'utf8')

  const plus = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 12 12" fill="none" stroke="#0F7F80" stroke-width="1.6" stroke-linecap="round"><path d="M6 1.5v9M1.5 6h9"/></svg>`

  const outline = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 600 600" fill="none">
  <circle cx="300" cy="300" r="120" stroke="#ffffff" stroke-width="1.2"/>
  <circle cx="300" cy="300" r="185" stroke="#ffffff" stroke-width="1.2"/>
  <circle cx="300" cy="300" r="250" stroke="#ffffff" stroke-width="1.2"/>
  <path d="M300 50a250 250 0 0 1 217 125" stroke="#D9F650" stroke-width="3"/>
  <path d="M118 452a250 250 0 0 1-25-152" stroke="#60DADB" stroke-width="3"/>
</svg>`

  const css = `/* Generated by scripts/gen-motifs.mjs — do not edit by hand. */
:root {
  --arc-mark: ${enc(mark)};
  --arc-outline: ${enc(outline)};
  --plus: ${enc(plus)};
}

.panel--statement {
  text-align: center;
}
.panel--statement h2 {
  margin-block-start: 1.25rem;
  max-width: 26ch;
  margin-inline: auto;
}
.panel--statement .panel__lead {
  max-width: 62ch;
  margin-inline: auto;
}
`
  await writeFile(path.join(ROOT, 'src', 'styles', 'motifs.css'), css, 'utf8')
  console.log('wrote assets/brand/arcs.svg, assets/brand/favicon.svg, src/styles/motifs.css')
}

main()
